name: analysis
channels:
    - conda-forge
dependencies:
  - root
  - pip
  - uproot3
  - uproot
  - awkward
  - pandas
  - pyarrow
  - numpy
  - matplotlib
  - lmfit
  - scikit-learn
  - pip:
      - vector
      - jupyterlab_latex
